CREATE TABLE MODULE_INFORMATION (
    MODULE_CODE VARCHAR(50) NOT NULL,
    MODULE_NAME VARCHAR(50) NOT NULL,
    CREDITS INT NOT NULL,
    CLASS_HOURS INT NOT NULL,
    NUM_WEEKS INT NOT NULL, 
    HOURS_SPENT INT NOT NULL
);

SELECT* FROM MODULE_INFORMATION

